### ISSUE TITLE
Bug : deleted pages called

### ISSUE THREAD

**Issue by Zatalyz** [solewniczak/dokuwiki-plugin-randompage2#2]
Hello,
I have tested the plugin on a wiki, it's seem good but sometimes, I have deleted pages who are called. 

Example : I deleted the page "hello" since fews month, but random page called it, so the "random page" who appear is a page "This page does not yet exist - You have followed a link to a page that does not yet exist. If your permissions are adequate, you can create it by clicking on " Create this page "." So strange :)

**Comment by solewniczak** [comment]
Now the existence of page is checked.
